  final int SCREENX=400;
  final int SCREENY=400;
  final int PIXELWIDTH=30;
  final int PIXELHEIGHT=25;
  final int MARGIN=30;
  final int DOWN = 0;
  final int LEFT = 1;
  final int RIGHT = 2;
  final int BASEFRAMERATE = 60;
